Sat Jun  6 15:21:55 +09 2020

diff --git a/scripts/build b/scripts/build
--- a/scripts/build
+++ b/scripts/build
@@ -466,19 +466,7 @@ done
 cd $P
 
 [ "$MAKE_KRESQ_IMAGE" ] && {
-
-[ "$KRESQ_PATH" ] || KRESQ_PATH=/tmp/openwrt_kresq
-[ -d "$KRESQ_PATH" ] && rm -rf $KRESQ_PATH
-[ -d "$KRESQ_PATH" ] || mkdir  $KRESQ_PATH
-
-echo "[i] KRESQ for $BOARDS">&2
-for B in $BOARDS; do
-#DL https://github.com/hyphop/khadas-uboot-spi/releases/download/openwrt/u-boot.$B.sd.bin || FAIL
-#DL https://github.com/hyphop/khadas-uboot/releases/download/openwrt/$B.u-boot.sd.bin || FAIL
-DL https://github.com/hyphop/khadas-uboot/releases/download/$UBOOT_REL/$B.u-boot.sd.bin || FAIL
-CMD cp $R $IMG_VFAT.boot/boot
-CMD mv $IMG_VFAT.boot $KRESQ_PATH/OW_BOOT
-done
+    echo ""
 }
 
 #echo no | mcat -i $F ::.automount.no
@@ -629,7 +617,20 @@ ls -l1 $IMG*
 
 
 [ "$MAKE_KRESQ_IMAGE" ] && {
-    
+
+[ "$KRESQ_PATH" ] || KRESQ_PATH=/tmp/openwrt_kresq
+[ -d "$KRESQ_PATH" ] && rm -rf $KRESQ_PATH
+[ -d "$KRESQ_PATH" ] || mkdir  $KRESQ_PATH
+
+echo "[i] KRESQ for $BOARDS">&2
+for B in $BOARDS; do
+#DL https://github.com/hyphop/khadas-uboot-spi/releases/download/openwrt/u-boot.$B.sd.bin || FAIL
+#DL https://github.com/hyphop/khadas-uboot/releases/download/openwrt/$B.u-boot.sd.bin || FAIL
+DL https://github.com/hyphop/khadas-uboot/releases/download/$UBOOT_REL/$B.u-boot.sd.bin || FAIL
+CMD cp $R $IMG_VFAT.boot/boot
+done
+CMD mv $IMG_VFAT.boot $KRESQ_PATH/OW_BOOT
+
     CMD mkdir $KRESQ_PATH/OW_DATA
     CMD cp $OWTMP.squashfs $KRESQ_PATH/OW_DATA
 
